//
// Created by arkadius on 09.03.19.
//

#ifndef INC_1_FILE_MANAGING_LIBRARY_LIBRARY_LOADER_H
#define INC_1_FILE_MANAGING_LIBRARY_LIBRARY_LOADER_H

void load_library();
#endif //INC_1_FILE_MANAGING_LIBRARY_LIBRARY_LOADER_H
